name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0  

      - name: Download SDL3 dependencies
        run: |
          ./install_win_deps.sh

      - name: Build all targets
        run: |
          zig build -Drelease

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            zig-out/derg-clock-popup-x86_64-windows.zip

